### ISSUE TITLE
Exception when running android-setup

### ISSUE THREAD

**Issue by elbowdonkey** [amirrajan/rubymotion-applied#138]
When running `motion android-setup` on macOS 10.15.7 I'm seeing an exception that I'm not quite sure how to get around.

```
Updating SDK...
Refresh Sources:
  Fetching https://dl.google.com/android/repository/addons_list-2.xml
  Validate XML
  Parse XML
  Fetched Add-ons List successfully
  Refresh Sources
  Fetching URL: https://dl.google.com/android/repository/repository-11.xml
  Validate XML: https://dl.google.com/android/repository/repository-11.xml
  Parse XML:    https://dl.google.com/android/repository/repository-11.xml
  Fetching URL: https://dl.google.com/android/repository/addon.xml
  Validate XML: https://dl.google.com/android/repository/addon.xml
  Parse XML:    https://dl.google.com/android/repository/addon.xml
  Fetching URL: https://dl.google.com/android/repository/glass/addon.xml
  Validate XML: https://dl.google.com/android/repository/glass/addon.xml
  Parse XML:    https://dl.google.com/android/repository/glass/addon.xml
  Fetching URL: https://dl.google.com/android/repository/extras/intel/addon.xml
  Validate XML: https://dl.google.com/android/repository/extras/intel/addon.xml
  Parse XML:    https://dl.google.com/android/repository/extras/intel/addon.xml
  Fetching URL: https://dl.google.com/android/repository/sys-img/android/sys-img.xml
  Validate XML: https://dl.google.com/android/repository/sys-img/android/sys-img.xml
  Parse XML:    https://dl.google.com/android/repository/sys-img/android/sys-img.xml
  Fetching URL: https://dl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Validate XML: https://dl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Parse XML:    https://dl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Fetching URL: https://dl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Validate XML: https://dl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Parse XML:    https://dl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Fetching URL: https://dl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Validate XML: https://dl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Parse XML:    https://dl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Fetching URL: https://dl.google.com/android/repository/sys-img/google_apis_playstore/sys-img.xml
  Validate XML: https://dl.google.com/android/repository/sys-img/google_apis_playstore/sys-img.xml
  Parse XML:    https://dl.google.com/android/repository/sys-img/google_apis_playstore/sys-img.xml
Error: Ignoring unknown package filter 'build-tools-29.0.5'
Error: Ignoring unknown package filter 'addon-google_apis-google-28'
Error: Ignoring unknown package filter 'sys-img-armeabi-v7a-addon-google_apis-google-28'
Error: Ignoring unknown package filter 'extra-android-support'
Warning: The package filter removed all packages. There is nothing to install.
         Please consider trying to update again without a package filter.
Installed NDK is up-to-date.
Exception in thread "Loading Sources" java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1012)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:966)
	at com.android.sdkuilib.internal.repository.core.PackagesDiffLogic.processLocals(PackagesDiffLogic.java:544)
	at com.android.sdkuilib.internal.repository.core.PackagesDiffLogic.access$000(PackagesDiffLogic.java:57)
	at com.android.sdkuilib.internal.repository.core.PackagesDiffLogic$UpdateOp.updateSourcePackages(PackagesDiffLogic.java:413)
	at com.android.sdkuilib.internal.repository.core.PackagesDiffLogic.updateSourcePackages(PackagesDiffLogic.java:502)
	at com.android.sdkuilib.internal.repository.ui.PackagesPageImpl$1.onUpdateSource(PackagesPageImpl.java:202)
	at com.android.sdklib.internal.repository.updater.PackageLoader$1.run(PackageLoader.java:231)
	at com.android.sdkuilib.internal.tasks.ProgressView$2.run(ProgressView.java:130)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

The exception occurs after the Android SDK Manager has launched. Eventually, the Android SDK Manager will close, and the `motion android-setup` command will continue and exit with this exception:

```
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.internal_new_GC(Unknown Source)
	at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
	at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
	at org.eclipse.swt.custom.CLabel.getTotalSize(Unknown Source)
	at org.eclipse.swt.custom.CLabel.computeSize(Unknown Source)
	at org.eclipse.swt.layout.FillData.computeSize(Unknown Source)
	at org.eclipse.swt.layout.FillLayout.computeChildSize(Unknown Source)
	at org.eclipse.swt.layout.FillLayout.computeSize(Unknown Source)
	at org.eclipse.swt.widgets.Composite.computeSize(Unknown Source)
	at org.eclipse.swt.widgets.Control.pack(Unknown Source)
	at org.eclipse.swt.widgets.Control.pack(Unknown Source)
	at org.eclipse.jface.window.ToolTip.toolTipShow(ToolTip.java:366)
	at org.eclipse.jface.window.ToolTip.access$5(ToolTip.java:356)
	at org.eclipse.jface.window.ToolTip$4.run(ToolTip.java:479)
	at org.eclipse.swt.widgets.Display.runTimers(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at com.android.sdkuilib.internal.repository.ui.SdkUpdaterWindowImpl2.open(SdkUpdaterWindowImpl2.java:148)
	at com.android.sdkuilib.repository.SdkUpdaterWindow.open(SdkUpdaterWindow.java:111)
	at com.android.sdkmanager.Main.showSdkManagerWindow(Main.java:413)
	at com.android.sdkmanager.Main.doAction(Main.java:391)
	at com.android.sdkmanager.Main.run(Main.java:151)
	at com.android.sdkmanager.Main.main(Main.java:117)
```

What else can I share to help troubleshoot this?

**Comment by Serlle** [comment]
What's up! @elbowdonkey, did you solve that problem? Practically the same thing happens to me
