### ISSUE TITLE
iOS 11 LocalAuthentication constants (enums) not available: LALABiometryTypeNone, LABiometryTypeFaceID, LABiometryTypeTouchID

### ISSUE THREAD

**Issue by hboon** [amirrajan/rubymotion-applied#45]
```
NSLog "supported: #{LAContext.new.biometryType}"
LABiometryTypeNone
LABiometryTypeFaceID
LABiometryTypeTouchID
NSLog "after"
```

Rakefile:

```
app.weak_frameworks << 'LocalAuthentication'
```

Crash with:

```
supported: 0
 app/app_delegate.rb:13:in `application:didFinishLaunchingWithOptions:': uninitialized constant AppDelegate::LABiometryTypeNone (NameError)
 *** Terminating app due to uncaught exception 'NameError', reason: 'app/app_delegate.rb:13:in `application:didFinishLaunchingWithOptions: ': uninitialized constant AppDelegate::LABiometryTypeNone (NameError)
```

RubyMotion 5.3
macOS Sierra 10.12.6 (16G29)

**Comment by amirrajan** [comment]
Added to short list.

**Comment by amirrajan** [comment]
```
typedef NS_ENUM(NSInteger, LABiometryType)
{
    /// The device does not support biometry.
    LABiometryNone,
    
   /// The device supports Touch ID.
    LABiometryTypeTouchID,
    
   /// The device supports Face ID.
    LABiometryTypeFaceID,
} NS_ENUM_AVAILABLE(NA, 11_0) __WATCHOS_UNAVAILABLE __TVOS_UNAVAILABLE;
```

Try: `LABiometryNone`

**Comment by amirrajan** [comment]
Reopen if needed.
